require_relative '../lib/Cli.rb'
require_relative '../lib/Game.rb'
require_relative '../lib/Deck.rb'
require_relative '../lib/Card.rb'
require_relative '../lib/Player.rb'
require_relative '../lib/players/Human.rb'
require_relative '../lib/players/Computer.rb'
